joinfaces:
  jsf:
    projectStage: Development
    faceletsSkipComments: true
    enableWebsocketEndpoint: true
  primefaces:
    theme: smoothness
    fontAwesome: true
  bootsfaces:
    getBootstrapFromCdn: false
server:
  servlet:
    session:
      timeout: 8H
spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 50MB  
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://localhost/histo5
    username: postgres
    password: postgres
  jpa:
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.time_zone: UTC
      hibernate.jdbc.lob.non_contextual_creation: true
  output:
    ansi:
      enabled: always
  aop:
    auto: false
  messages:
    basename: messages/messages
  freemarker:
    checkTemplateLocation:  false

logging:
  file: test.log
  path: D:/
  level: 
    org:
      springframework:
        security: ERROR
      # disable lob error
      hibernate:
        engine: 
          jdbc:
            env:
              internal:
                LobCreatorBuilderImpl: ERROR
patho:
  common:
     ####### Task View #######
    taskView:
      tasksPerPage: 50
      tasksPerPageOptions:
        - 50
        - 100
        - 200
        - 300
  ####### LDAP #######
  ldap:
    ldapUrl: ldap://ldap.ukl.uni-freiburg.de/
    baseDn: dc=ukl,dc=uni-freiburg,dc=de
    userParentDn: people
    userDn: uid
  ####### JWT #######
  jwt:   
    secret: 7w!z%C*F)J@NcRfUjXn2r5u8x/A?D(G+
    tokenPrefix: Bearer 
    headerString: Authorization
  ####### JSON #######
  json:
    patientByPizUrl: http://auginfo/piz/$piz
    patientByNameSurnameBirthday: http://auginfo/piz?name=$name&vorname=$surname&geburtsdatum=$birthday
  ###### FAX  ######
  fax:
    faxPost: http://augimageserver:3033/$number
    faxStatus: http://augimageserver:3033/query_status/$id
  ####### SETTINGS #######
  printer:
    cupsPrinter:
      host: 10.210.21.254/printers/
      port: 631
      printerForRoom: http://10.210.21.11:3009/DB/PLS/ip2room/ip/$ip
    lablePrinter:
      printer:
        -
          name: Aug-Histo-Etikettendrucker-1
          id: 1
          location: Histologie-Labor
          address: 10.250.7.242
          port: 21
          userName: admin
          password: 1234
          timeout: 1000
        -
          name: Aug-Histo-Etikettendrucker-2
          id: 2
          location: Histologie-Labor
          address: 10.250.7.239
          port: 21
          userName: admin
          password: 1234
          timeout: 1000     
  taskService:
    taskArchiveRules:
      blockingFavouriteLists:
        - StainingList
        - DiagnosisList
        - NotificationList
        - ReStainingList
        - ReDiagnosisList
        - StayInStainingList
        - StayInDiagnosisList
        - StayInNotificationList
        - CouncilSendRequestMTA
        - CouncilSendRequestSecretary
        - CouncilRequest
        - CouncilCompleted
        - Council
        - CouncilWaitingForReply
        - CouncilReplyPresent
  ####### SETTINGS ####### 
  settings:
    ####### MAIL #######
    mail:
      settings:
        server: smtp.ukl.uni-freiburg.de
        port: 465
        ssl: true
        debug: false
        systemMail: augenklinik.histologie@uniklinik-freiburg.de
        systemName: Histologisches Labor der Augenklinik Freiburg
        adminAddresses:
          - andreas.glatz@uniklinik-freiburg.de
        errorAddresses:
          - andreas.glatz@uniklinik-freiburg.de
      mails:
        -
          id: 0
          templateName: org.histo.template.mail.SuccessUnlockMail
          defaultOfType: true
          name: Benutzer-Freischaltung erfolgt
          content: classpath:templates/mail/successUnlock.txt
        -
          id: 1
          templateName: org.histo.template.mail.RequestUnlockMail
          name: Benutzer-Freischaltung erbeten
          defaultOfType: true
          content: classpath:templates/mail/requestUnlock.txt
        -
          id: 2
          templateName: org.histo.template.mail.DiagnosisReportMail
          name: Diagnose-Benachrichtigung
          defaultOfType : true
          content: classpath:templates/mail/diagnosisReport.txt
        -
          id: 3
          templateName: org.histo.template.mail.ErrorMail
          name: Fehlermeldung!
          defaultOfType : true
          content: classpath:templates/mail/error.txt
    fileSettings:
      thumbnailDPI: 50
      fileRepository: D:/patho
      workDirectory: fileRepository:pdf
      auxDirectory: fileRepository:pdf/tmp
      errorDirectory: fileRepository:pdf/error
      printDirectory: fileRepository:pdf/print
      programInfo: fileRepository:.patho
      programVersionInfo: classpath:settings/version.txt
      copyFromClasspathToWorkDirectory:
        - "classpath:templates/print/_*"
      cleanup: true
      keepErrorFiles: true
    defaultDocuments:
      diagnosisApprovedDocument: 10
      diagnosisReportForUsers: 10
      taskCreationDocument: 2
      notificationDefaultEmailDocument: 10
      notificationDefaultEmail: 2
      notificationDefaultFaxDocument: 10
      notificationDefaultLetterDocument: 10
      notificationDefaultPrintDocument: 11
      notificationSendReport: 1000
      slideLabelDocument: 100
      slideLableTestDocument: 150
      printerTestDocument: 0
      emptyPage: classpath:templates/print/emptyPage.pdf
      lablePrinterTestPage: test.zpl
      cupsPrinterTestPage: classpath:templates/print/testPage.pdf      
    defaultNotification:
      defaultNotifications:
        -
          role: SURGEON
          notificationTyps: 
            -
              EMAIL
        -
          role: CLINIC_PHYSICIAN
          notificationTyps:
            -
              EMAIL
        -
          role: EXTERNAL_SURGEON
          notificationTyps:
            -
              LETTER
    miscellaneous:
      phoneRegex: "^\\s*(?:[\\+#]?(\\d{1,3}))?([-. ()/\\\\]*(\\d*))*?\\s*$"
    schedule:
      pdfCleanupCron: '5 21 * * * *'
  ####### Print Documents #######
    documents:
      - 
        id: 0
        name: Eingangsbogen
        content: classpath:templates/print/USchein_full.tex
        alternateContent:
        type: U_REPORT
        attributes:
        templateName: com.patho.main.template.print.CaseCertificate
        uiClass: com.patho.main.dialog.print.documentUi.CaseCertificateUi
        defaultOfType: false
        transientContent: true
        hidden: false
        sharedContextGroup: 2
      -
        id: 1
        name: Eingangsbogen bedrucken
        content: classpath:templates/print/USchein_empty.tex
        alternateContent: ""
        type: U_REPORT_EMTY
        attributes: 
        templateName: com.patho.main.template.print.CaseCertificate
        uiClass: com.patho.main.dialog.print.documentUi.CaseCertificateUi
        defaultOfType: false
        transientContent: true
        hidden: false
        sharedContextGroup: 2
      -
        id: 2
        name: Eingangsbogen bedrucken, umgekehrt
        content: classpath:templates/print/USchein_empty_rotated180.tex
        alternateContent: ""
        type: U_REPORT_EMTY
        attributes: media:keyword:default,tray1
        templateName: com.patho.main.template.print.CaseCertificate
        uiClass: com.patho.main.dialog.print.documentUi.CaseCertificateUi
        defaultOfType: false
        transientContent: true
        hidden: false
        sharedContextGroup: 2
      -
        id: 10
        name: Befundbericht
        content: classpath:templates/print/Report_Intern.tex
        alternateContent: ""
        type: DIAGNOSIS_REPORT
        attributes: sides:keyword:one-side
        templateName: com.patho.main.template.print.DiagnosisReport
        uiClass: com.patho.main.dialog.print.documentUi.DiagnosisReportUi
        defaultOfType: true
        transientContent: false
        hidden: false
        duplexPrinting: true
        printEvenPageCount: true
        sharedContextGroup: 1
      -
        id: 11
        name: Befundbericht - ohne Logo
        content: classpath:templates/print/Report_Intern_noLogo.tex
        alternateContent: ""
        type: DIAGNOSIS_REPORT
        attributes: "sides:keyword:one-side#media:keyword:default,tray2"
        templateName: com.patho.main.template.print.DiagnosisReport
        uiClass: com.patho.main.dialog.print.documentUi.DiagnosisReportUi
        defaultOfType: false
        transientContent: false
        hidden: false
        duplexPrinting: true
        printEvenPageCount: true
        sharedContextGroup: 1
      -
        id: 20
        name: Befundbericht extern
        content: classpath:templates/print/Report_Extern.tex
        alternateContent: ""
        type: DIAGNOSIS_REPORT_EXTERN
        attributes: sides:keyword:one-side
        templateName: com.patho.main.template.print.DiagnosisReport
        uiClass: com.patho.main.dialog.print.documentUi.DiagnosisReportUi
        defaultOfType: true
        transientContent: false
        hidden: false
        duplexPrinting: true
        printEvenPageCount: true
        sharedContextGroup: 1
      -
        id: 21
        name: Befundbericht extern - ohne Logo
        content: classpath:templates/print/Report_Extern_noLogo.tex
        alternateContent: ""
        type: DIAGNOSIS_REPORT_EXTERN
        attributes: "sides:keyword:one-side#media:keyword:default,tray2"
        templateName: com.patho.main.template.print.DiagnosisReport
        uiClass: com.patho.main.dialog.print.documentUi.DiagnosisReportUi
        defaultOfType: true
        transientContent: false
        hidden: false
        duplexPrinting: true
        printEvenPageCount: true
        sharedContextGroup: 1
      -
        id: 50
        name: Konsil
        content: classpath:templates/print/council.tex
        alternateContent: ""
        type: COUNCIL_REQUEST
        attributes: 
        templateName: com.patho.main.template.print.CouncilReport
        uiClass: com.patho.main.dialog.print.documentUi.CouncilReportUi
        defaultOfType: true
        transientContent: false
        hidden: false
      -
        id: 100
        name: Default Slide Lable
        content: classpath:templates/print_label/defaultLable.zpl
        alternateContent: ""
        type: LABLE
        attributes: 
        templateName: com.patho.main.template.print.SlideLable
        defaultOfType: true
        transientContent: false
        hidden: false
      -
        id: 150
        name: Test Slide Lable
        content: classpath:templates/print_label/testLable.zpl
        alternateContent: ""
        type: TEST_LABLE
        attributes: 
        templateName: com.patho.main.template.print.SlideLable
        defaultOfType: true
        transientContent: false
        hidden: false
      -
        id: 1000
        name: Send Report
        content: classpath:templates/print/SendReport.tex
        alternateContent: ""
        attributes: 
        type: NOTIFICATION_SEND_REPORT
        templateName: com.patho.main.template.print.SendReport
        defaultOfType: true
        transientContent: false
        hidden: false
      
           
              